# Generated by Django 5.2.4 on 2025-07-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_unique_constraint_test_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
