# Generated by Django 5.2.5 on 2025-08-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay'), ('manual', 'Manual'), ('mock', 'Mock Gateway (Development)')], max_length=20),
        ),
    ]
