# Generated by Django 5.2.4 on 2025-07-29 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi_select', 'Multiple Select'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('essay', 'Essay/Descriptive')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10)),
                ('marks', models.IntegerField(default=1)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expected_answer', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_banks',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True)),
                ('boolean_answer', models.BooleanField(blank=True, null=True)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_answers',
            },
        ),
    ]
