# Generated by Django 5.2.4 on 2025-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list, help_text='List of acceptable answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in seconds', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('computer_science', 'Computer Science'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='default_difficulty',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='default_marks',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
