# Generated by Django 5.2.4 on 2025-08-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionbank_avg_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View Only'), ('edit', 'View & Edit'), ('copy', 'View & Copy Questions'), ('full', 'Full Access (View, Edit, Copy)')], default='view', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent access', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this permission')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='questions.questionbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_bank_permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='question_ba_user_id_cccc58_idx'), models.Index(fields=['question_bank', 'is_active'], name='question_ba_questio_0ff6c4_idx')],
                'unique_together': {('question_bank', 'user')},
            },
        ),
    ]
